---
- name: Copy tftp files
  copy:
    src: files/tftp/{{ item }}
    dest: /var/lib/tftpboot/
    owner: root
    group: root
    mode: '0644'
  loop:
    - undionly.kpxe
    - bootstrap.ipxe
    - ipxe.efi

- name: Enable razor server
  systemd:
        name: razor-server
        enabled: true

- name: initialize database
  become: yes
  become_user: razor
  command: /opt/puppetlabs/bin/razor-admin -e production migrate-database

- name: Restart razor service
  service:
    name: razor-server
    state: restarted
