---
- name: Install packages to make live easier.
  package:
    name: vim
    state: present

- name: Include tftp config tasks
  include: tftp.yml

- name: Include dhcpd config tasks
  include: dhcpd.yml

- name: Enable razor server
  systemd:
        name: razor-server
        enabled: true

- name: initialize database
  become: yes
  become_user: razor
  command: /opt/puppetlabs/bin/razor-admin -e production migrate-database

- name: Restart razor service
  service:
    name: razor-server
    state: restarted
